import {REGEX, REGEX_TEXT} from './REGEX';
import {NOT_REQUIRE_LOGIN_PAGE_ID, PAGE_ID_TO_ROUTE, REQUIRE_LOGIN_PAGE_ID, ROUTE_TO_PAGE_ID} from './ROUTE';
import CAROUSEL_IMAGE from './CAROUSEL_IMAGE';

export {
    REGEX,
    REGEX_TEXT,
    NOT_REQUIRE_LOGIN_PAGE_ID,
    REQUIRE_LOGIN_PAGE_ID,
    PAGE_ID_TO_ROUTE,
    ROUTE_TO_PAGE_ID,
    CAROUSEL_IMAGE,
};