import REQUIRE_LOGIN_PAGE_ID from './REQUIRE_LOGIN_PAGE_ID';
import NOT_REQUIRE_LOGIN_PAGE_ID from './NOT_REQUIRE_LOGIN_PAGE_ID';

// 页面的路由，用于在 React-Router 中使用
export default {
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_INSURANCE_LIST]: '/insuranceList',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_INSURANCE_PUBLICATION]: '/insurancePublication',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_DIRECT_PAYMENT_PROCESS]: '/directPaymentProcess',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_DIRECT_PAYMENT_DETAIL]: '/directPaymentDetail',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_INSURANCE_PURCHASING_PROCESS]: '/insurancePurchasingProcess',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_INSURANCE_PURCHASING_DETAIL]: '/insurancePurchasingDetail',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_PERSONAL_CENTER]: '/personalCenter',
    [REQUIRE_LOGIN_PAGE_ID.HOSPITAL_INSURANCE_DETAIL]: '/insuranceDetail',
    [NOT_REQUIRE_LOGIN_PAGE_ID.HOSPITAL_LOGIN]: '/login',
    [NOT_REQUIRE_LOGIN_PAGE_ID.HOSPITAL_SIGN_UP]: '/signUp',
};