// 页面的 ID，目前设想用于识别当前所在页面
export default {
    HOSPITAL_INSURANCE_LIST: Symbol('HOSPITAL_INSURANCE_LIST'),
    HOSPITAL_INSURANCE_PUBLICATION: Symbol('HOSPITAL_INSURANCE_PUBLICATION'),
    HOSPITAL_DIRECT_PAYMENT_PROCESS: Symbol('HOSPITAL_DIRECT_PAYMENT_PROCESS'),
    HOSPITAL_DIRECT_PAYMENT_DETAIL: Symbol('HOSPITAL_DIRECT_PAYMENT_DETAIL'),
    HOSPITAL_INSURANCE_PURCHASING_PROCESS: Symbol('HOSPITAL_INSURANCE_PURCHASING_PROCESS'),
    HOSPITAL_INSURANCE_PURCHASING_DETAIL: Symbol('HOSPITAL_INSURANCE_PURCHASING_DETAIL'),
    HOSPITAL_PERSONAL_CENTER: Symbol('HOSPITAL_PERSONAL_CENTER'),
    HOSPITAL_INSURANCE_DETAIL: Symbol('HOSPITAL_INSURANCE_DETAIL'),
    HOSPITAL_SUBMIT_MEDICAL_RECORD: Symbol('HOSPITAL_SUBMIT_MEDICAL_RECORD'),
    HOSPITAL_QUERY_MEDICAL_RECORD: Symbol('HOSPITAL_QUERY_MEDICAL_RECORD'),
};